# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - build-v1-{{ arch }}-{{ checksum "requirements.pip" }}
          - build-v1-{{ arch }}-{{ .Branch }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.pip

      - save_cache:
          paths:
            - ./venv
          key: build-v1-{{ arch }}-{{ checksum "requirements.pip" }}
      - save_cache:
          paths:
            - ./venv
          key: build-v1-{{ arch }}-{{ .Branch }}

      - run:
          name: Build site
          command: |
            . venv/bin/activate
            inv build

      - persist_to_workspace:
          root: .
          paths:
          - output

  deploy:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "39:e9:18:49:de:6f:20:27:9d:4a:24:48:12:1e:99:a3"
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Expose user pip-installed binaries on path
          command: echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
      - run:
          name: Deploy to github pages
          command: |
            pip install --user ghp-import
            cp -R .circleci output/
            ghp-import --cname=getudata.org -m "Deploy getudata.org" --push output

workflows:
  version: 2
  build-and-deploy:
    jobs:
      # Build on any branch except github pages
      - build:
          filters:
            branches:
              ignore: gh-pages
      # Deploy only on master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
